spring.application.name=demo

spring.data.mongodb.uri=mongodb://localhost:27017/MusicPlayer

supabase.jwt.secret=28c0ba07-6b83-46a1-93a2-0edf0297057b
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://yeldrfvmqtzmnulotmgj.supabase.co/auth/v1
